version: '3'

services:
  discord_bot:
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
    env_file:
      - ./config/.env
    stdin_open: true
    tty: true
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./config/.env
    expose:
      - "5432"
