"""empty message

Revision ID: f69c9f1ec37d
Revises: 02e96b27ab7c
Create Date: 2024-06-27 10:31:26.498417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f69c9f1ec37d"
down_revision: Union[str, None] = "02e96b27ab7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gamble_data", sa.Column("guild", sa.String(), nullable=False))
    op.drop_constraint("gamble_data_guild_id_fkey", "gamble_data", type_="foreignkey")
    op.create_foreign_key(None, "gamble_data", "guild", ["guild"], ["id"])
    op.drop_column("gamble_data", "guild_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamble_data",
        sa.Column("guild_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "gamble_data", type_="foreignkey")
    op.create_foreign_key(
        "gamble_data_guild_id_fkey", "gamble_data", "guild", ["guild_id"], ["id"]
    )
    op.drop_column("gamble_data", "guild")
    # ### end Alembic commands ###
